### ISSUE TITLE
Sonar should enforce maximum mining requirements

### ISSUE THREAD

**Issue by samsontmr** [OpenMined/PySonar#11]
Submitted gradients should only be accepted if there are at least 10 gradients from another miner in between submissions

**Comment by anoff** [comment]
Shouldn't this be reopened? Don't have access to the repo but I'm pretty sure this is part of hydrogen :)

**Comment by samsontmr** [comment]
This should be in Sonar, right? I recreated it in Sonar after realizing this was the client-side library :)

**Comment by anoff** [comment]
oh you're right. Seems like I fell into the same trap haha
