### ISSUE TITLE
dockerize the notebook

### ISSUE THREAD

**Issue by anoff** [OpenMined/PySonar#12]
The (main) demo notebook within pysonar should be dockerized to allow running the platform using only `docker` and no local installations.

**Acceptance Criteria**:
* [Main notebook](https://github.com/OpenMined/PySonar/blob/master/notebooks/Sonar%20-%20Decentralized%20Model%20Training%20Simulation%20(local%20blockchain).ipynb) is automatically initialised when starting the container
* (default) jupyter port is exposed to host system
* container connects to blockchain container (see Sonar)
* runs it's own `IPFS` node

**Comment by TheOriginalAlex** [comment]
@anoff: Why `docker` only start up?  docker-compose would make it easier by breaking the entire setup into micro services.

**Comment by anoff** [comment]
@TheOriginalAlex I changed the wording on the issue, nothing speaks against docker-compose :) It's just that *everything* should be docker. Does it make sense now?
