### ISSUE TITLE
unexpected keyword argument: 'ipfs_host'

### ISSUE THREAD

**Issue by anoff** [OpenMined/PySonar#19]
Working on the latest `develop` branch (9211ba0) I get the following error when trying to run the second cell:

![image](https://user-images.githubusercontent.com/7142618/29485620-f79ac7d6-84d4-11e7-9561-4a66ae59a4e7.png)

**Comment by anoff** [comment]
Ok that was a rubberducking issue. Turns out I didn't `python setup.py install` after pulling. _Remember to use docker_

**Comment by nikhilaravi** [comment]
@anoff I'm getting this same error even after I run `python setup.py install`.  Is there anything else I could do to resolve the issue?
