### ISSUE TITLE
improve tooling

### ISSUE THREAD

**Issue by anoff** [OpenMined/PySonar#3]
It should be easier to get the demo running. Possible solution: package all the prerequisites into a docker container that hosts the latest version of the `notebook` and expose the jupyter port to the host.

**Comment by iamtrask** [comment]
just initialized a dockerhub account.

**Comment by iamtrask** [comment]
@TheOriginalAlex @anoff was this ticket full addressed by the merged pull request?

**Comment by anoff** [comment]
fixed with #10
