### ISSUE TITLE
docker-compose up command is not running with version 3

### ISSUE THREAD

**Issue by amiteshP** [OpenMined/PySonar#53]
**System** : Ubuntu17.04

**Steps**: Run the "docker-compose up" command in the PySonar repository.

**Result**:

$ **sudo docker-compose up**
 >>ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

**Workaround** ::
Changed the version from 3 to 2 in the docker-compose.yml file present in the PySonar directory, and now it is able to run successfully.

**Purpose** ::
Reporting here so that we can solve this issue in future if it comes up.

**Comment by axelhodler** [comment]
Your `docker-compose` version is too old and does not support version 3 files. Here's the process to update to the newest (1.16.1) version: https://github.com/docker/compose/releases

**Comment by amiteshP** [comment]
@axelhodler  Thanks! Worked. :+1:

**Comment by udaykumartadka** [comment]
@axelhodler Thanks!! as I'm trying to install on Linux, so the link https://docs.docker.com/compose/install/#install-compose also worked for me
